import type { Plan } from '@/types/plans'

export const SME_PLANS: Plan[] = [
  {
    id: 'spark',
    tier: 'Spark',
    label: 'SME 01',
    segment: 'sme',
    description: 'Get your team working with private AI this week. Up to 50 users. No technical setup on your side.',
    setupUSD: 618,
    monthlyUSD: 499,
    annualUSD: 5090,
    minimumTermMonths: 3,
    firstPaymentUSD: 618 + (499 * 3),
    gpu: 'Shared AI Server',
    vram: 'Shared infrastructure',
    gpuColor: '#3b6d11',
    userLimit: 'Up to 50 users',
    userCount: 50,
    features: [
      'Private AI chat interface — accessible from any browser',
      'Your documents become searchable — query files by asking questions',
      'Centralised AI Workspace for staff',
      'Up to 50 team members',
      'Email support',
      'Managed hosting, security, and updates',
    ],
    interfaces: ['AI Chat Interface', 'Centralised Workspace', 'API'],
    featured: false,
    isSME: true,
    targetSectors: ['Startups', 'Small businesses', 'Micro-businesses'],
    aiModels: ['Qwen3-30B Q6', 'DeepSeek-R1-32B Q6'],
    concurrentSessions: 10,
  },
  {
    id: 'grow',
    tier: 'Grow',
    label: 'SME 02',
    segment: 'sme',
    description: 'Scale AI across your whole organisation. Up to 100 users, multiple interfaces, full API access.',
    setupUSD: 372,
    monthlyUSD: 750,
    annualUSD: 7650,
    minimumTermMonths: 3,
    firstPaymentUSD: 372 + (750 * 3),
    gpu: 'Shared AI Server',
    vram: 'Shared infrastructure',
    gpuColor: '#3b6d11',
    userLimit: 'Up to 100 users',
    userCount: 100,
    features: [
      'Everything in Spark',
      'Two AI capabilities for different task types',
      'Connect AI to your existing tools and apps',
      'Up to 100 team members',
      'Support with 48-hour response',
      'Monthly usage and performance report',
    ],
    interfaces: ['AI Chat Interface', 'Centralised Workspace', 'API'],
    featured: true,
    isSME: true,
    targetSectors: ['Growing teams', 'SMEs', 'Agencies'],
    aiModels: ['Qwen3-30B Q6', 'DeepSeek-R1-32B Q6'],
    concurrentSessions: 10,
  },
  {
    id: 'build',
    tier: 'Build',
    label: 'SME 03',
    segment: 'sme',
    description: 'For technical teams that want AI in everything — writing, research, code, and automation.',
    setupUSD: 372,
    monthlyUSD: 1125,
    annualUSD: 11475,
    minimumTermMonths: 3,
    firstPaymentUSD: 372 + (1125 * 3),
    gpu: 'Shared AI Server',
    vram: 'Shared infrastructure',
    gpuColor: '#3b6d11',
    userLimit: 'Up to 125 users',
    userCount: 125,
    features: [
      'Everything in Grow',
      'Three specialised AI capabilities including coding assistance',
      'Developer AI Tools built into your existing workflow',
      'AI Automation Suite — agents run tasks overnight',
      'Webhook and API integrations',
      'Priority support with 24-hour response',
    ],
    interfaces: ['AI Chat Interface', 'Centralised Workspace', 'Automation Suite', 'Developer Tools', 'API'],
    featured: false,
    isSME: true,
    targetSectors: ['Tech teams', 'Digital agencies', 'Developer teams'],
    aiModels: ['Qwen3-30B Q6', 'DeepSeek-R1-32B Q6', 'Qwen2.5-Coder-32B Q6'],
    concurrentSessions: 12,
  },
]

export const ENTERPRISE_PLANS: Plan[] = [
  {
    id: 'seed',
    tier: 'Seed',
    label: 'Tier 01',
    segment: 'enterprise',
    description: 'A complete private AI environment on dedicated infrastructure. Unlimited users. Live in 14 days.',
    setupUSD: 1600,
    monthlyUSD: 1500,
    annualUSD: 15300,
    minimumTermMonths: 3,
    firstPaymentUSD: 1600 + (1500 * 3),
    gpu: 'Dedicated AI Server',
    vram: 'Dedicated infrastructure',
    gpuColor: '#185fa5',
    userLimit: 'Unlimited users',
    userCount: 999,
    features: [
      'Dedicated AI server allocated entirely to your organisation',
      'Three specialised AI capabilities configured for your use cases',
      'Your documents become searchable across your entire knowledge base',
      'Connect AI to your apps and internal tools via API',
      'Centralised AI Workspace — staff access everything from one browser tab',
      'Monthly performance and usage report',
      'Managed updates and round-the-clock monitoring',
    ],
    interfaces: ['AI Chat Interface', 'Centralised Workspace', 'API'],
    featured: false,
    isSME: false,
    targetSectors: ['Schools', 'NGOs', 'Small enterprises'],
    aiModels: ['Qwen3-30B Q8', 'DeepSeek-R1-32B Q8', 'Qwen2.5-32B Q8'],
    concurrentSessions: 20,
  },
  {
    id: 'scale',
    tier: 'Scale',
    label: 'Tier 02',
    segment: 'enterprise',
    description: 'AI across every department. Unlimited users. Dedicated high-performance infrastructure.',
    setupUSD: 3420,
    monthlyUSD: 3150,
    annualUSD: 32130,
    minimumTermMonths: 3,
    firstPaymentUSD: 3420 + (3150 * 3),
    gpu: 'Dedicated High-Performance Server',
    vram: 'Dedicated infrastructure',
    gpuColor: '#0f6e56',
    userLimit: 'Unlimited users',
    userCount: 999,
    features: [
      'Everything in Seed',
      'High-performance dedicated AI server',
      'Multiple concurrent AI capabilities running simultaneously',
      'Department-separated knowledge bases',
      'Developer AI Tools for engineering teams',
      'AI Automation Suite for overnight agent workflows',
      'Priority support and quarterly strategy review',
    ],
    interfaces: ['AI Chat Interface', 'Centralised Workspace', 'Automation Suite', 'Developer Tools', 'API'],
    featured: true,
    isSME: false,
    targetSectors: ['Enterprises', 'Hospitals', 'Financial services'],
    aiModels: ['DeepSeek-R1-70B Q4', 'Llama 3.3-70B Q4', 'Qwen2.5-72B Q4', 'Qwen2.5-Coder-32B Q8'],
    concurrentSessions: 70,
  },
  {
    id: 'sovereign',
    tier: 'Sovereign',
    label: 'Tier 03',
    segment: 'enterprise',
    description: 'Maximum capability. Unlimited users. Custom AI configuration. Dedicated account manager.',
    setupUSD: 3520,
    monthlyUSD: 5670,
    annualUSD: 57834,
    minimumTermMonths: 3,
    firstPaymentUSD: 3520 + (5670 * 3),
    gpu: 'Dedicated Premium Server',
    vram: 'Dedicated infrastructure',
    gpuColor: '#854f0b',
    userLimit: 'Unlimited users',
    userCount: 999,
    features: [
      'Everything in Scale on premium dedicated infrastructure',
      'Largest available AI models for complex reasoning tasks',
      'Custom AI capability configuration for your organisation',
      'Multi-department automation agent deployments',
      'Dedicated CPU cluster for your web and application workloads',
      'Custom model fine-tuning on your organisation data',
      'Dedicated Garium account manager and custom SLA',
    ],
    interfaces: ['AI Chat Interface', 'Centralised Workspace', 'Automation Suite', 'Developer Tools', 'API', 'Custom'],
    featured: false,
    isSME: false,
    targetSectors: ['Large enterprises', 'Government', 'Healthcare systems'],
    aiModels: ['Qwen2.5-72B Q8', 'DeepSeek-R1-70B Q8', 'Llama 3.3-70B Q8', 'Qwen3-235B Q2'],
    concurrentSessions: 140,
  },
]

export const ALL_PLANS = [...SME_PLANS, ...ENTERPRISE_PLANS]
