import type { Plan } from '@/types/plans'

export const SME_PLANS: Plan[] = [
  {
    id: 'spark', tier: 'Spark', label: 'SME 01', segment: 'sme',
    description: 'Private AI essentials for solo founders and small teams. Up and running in days, not weeks.',
    setupUSD: 630, monthlyUSD: 375, annualUSD: 3825,
    gpu: 'Shared L40S', vram: 'Shared node', gpuColor: '#3b6d11',
    userLimit: 'Up to 5 users',
    features: [
      'Private AI chat interface (Open WebUI)',
      'Document intelligence — query your own files',
      'One AI model (Qwen3-30B)',
      'Staff workstation access via Guacamole',
      'Email support',
      'Managed hosting and updates',
    ],
    interfaces: ['Open WebUI', 'Guacamole', 'API'],
    featured: false, isSME: true,
    targetSectors: ['Startups', 'Micro-businesses', 'Freelancers'],
  },
  {
    id: 'grow', tier: 'Grow', label: 'SME 02', segment: 'sme',
    description: 'For growing teams that need AI across multiple roles without per-seat pricing.',
    setupUSD: 1260, monthlyUSD: 750, annualUSD: 7650,
    gpu: 'Shared L40S', vram: 'Shared node', gpuColor: '#3b6d11',
    userLimit: 'Up to 15 users',
    features: [
      'Everything in Spark',
      'Two AI models for different task types',
      'LibreChat interface option',
      'API access for your own apps and tools',
      'Staff workstation access via Guacamole',
      'Slack and email support with 48-hour response',
      'Monthly usage report',
    ],
    interfaces: ['Open WebUI', 'LibreChat', 'Guacamole', 'API'],
    featured: true, isSME: true,
    targetSectors: ['SMEs', 'Growing teams', 'Agencies'],
  },
  {
    id: 'build', tier: 'Build', label: 'SME 03', segment: 'sme',
    description: 'For technical teams and agencies who want AI embedded in their products and workflows.',
    setupUSD: 1890, monthlyUSD: 1125, annualUSD: 11475,
    gpu: 'Shared L40S', vram: 'Shared node', gpuColor: '#3b6d11',
    userLimit: 'Up to 30 users',
    features: [
      'Everything in Grow',
      'Three AI models including a coding-optimised model',
      'VSCode AI extension for developer teams',
      'OpenClaw agent interface for automation',
      'Webhook and API integrations',
      'Priority support with 24-hour response',
    ],
    interfaces: ['Open WebUI', 'LibreChat', 'OpenClaw', 'Guacamole', 'VSCode', 'API'],
    featured: false, isSME: true,
    targetSectors: ['Tech teams', 'Digital agencies', 'PR firms'],
  },
]

export const ENTERPRISE_PLANS: Plan[] = [
  {
    id: 'seed', tier: 'Seed', label: 'Tier 01', segment: 'enterprise',
    description: 'A complete private AI environment for smaller organisations, schools, and institutions.',
    setupUSD: 3150, monthlyUSD: 1500, annualUSD: 15300,
    gpu: 'NVIDIA L40S', vram: '48GB VRAM', gpuColor: '#185fa5',
    userLimit: 'Up to 25 users',
    features: [
      'Dedicated NVIDIA L40S GPU server',
      'Three AI models deployed and configured',
      'Document intelligence and knowledge base',
      'API access for app integrations',
      'Staff workstation access via Guacamole',
      'Monthly performance and usage report',
      'Managed updates and 24-hour monitoring',
    ],
    interfaces: ['Open WebUI', 'LibreChat', 'Guacamole', 'API'],
    featured: false, isSME: false,
    targetSectors: ['Schools', 'NGOs', 'Small enterprises'],
  },
  {
    id: 'scale', tier: 'Scale', label: 'Tier 02', segment: 'enterprise',
    description: 'Full-organisation AI platform for enterprises deploying AI across departments.',
    setupUSD: 6300, monthlyUSD: 3150, annualUSD: 32130,
    gpu: 'NVIDIA H100', vram: '94GB VRAM', gpuColor: '#0f6e56',
    userLimit: 'Up to 100 users',
    features: [
      'Dedicated NVIDIA H100 GPU server',
      'Multiple concurrent model deployments',
      'VSCode AI extension for developer teams',
      'OpenClaw and ZeroClaw agent interfaces',
      'Department-separated knowledge bases',
      'Priority support and quarterly strategy review',
      'Grafana client dashboard included',
    ],
    interfaces: ['Open WebUI', 'LibreChat', 'OpenClaw', 'ZeroClaw', 'Guacamole', 'VSCode', 'API'],
    featured: true, isSME: false,
    targetSectors: ['Enterprises', 'Hospitals', 'Financial services'],
  },
  {
    id: 'sovereign', tier: 'Sovereign', label: 'Tier 03', segment: 'enterprise',
    description: 'Maximum capacity for large organisations requiring compliance, scale, and white-glove management.',
    setupUSD: 12600, monthlyUSD: 5670, annualUSD: 57834,
    gpu: 'NVIDIA H200', vram: '141GB VRAM', gpuColor: '#854f0b',
    userLimit: 'Unlimited users',
    features: [
      'Dedicated NVIDIA H200 GPU server',
      'Capacity for 70B parameter models',
      'Multi-department agent deployments',
      'Custom model fine-tuning on organisation data',
      'Dedicated CPU cluster for web and app workloads',
      'Dedicated Garium account manager',
      'Custom SLA agreement',
    ],
    interfaces: ['Open WebUI', 'LibreChat', 'OpenClaw', 'ZeroClaw', 'Guacamole', 'VSCode', 'API', 'Custom'],
    featured: false, isSME: false,
    targetSectors: ['Large enterprises', 'Government', 'Healthcare systems'],
  },
]

export const ALL_PLANS = [...SME_PLANS, ...ENTERPRISE_PLANS]
