import type { Plan } from '@/types/plans'

export const SME_PLANS: Plan[] = [
  {
    id: 'spark', tier: 'Spark', label: 'SME 01', segment: 'sme',
    description: 'Private AI essentials for solo founders and small teams. Up and running in days, not weeks.',
    setupUSD: 630, monthlyUSD: 375, annualUSD: 3825,
    gpu: 'Private shared infrastructure', vram: 'Shared node', gpuColor: '#3b6d11',
    userLimit: 'Up to 5 users',
    features: [
      'Private AI workspace your team accesses from any browser',
      'Ask questions across your own documents and files',
      'One frontier AI model, configured for your organisation',
      'Up to 5 team members',
      'Email support',
      'Fully managed — updates and monitoring included',
    ],
    interfaces: ['AI chat interface', 'Private workspace', 'API'],
    featured: false, isSME: true,
    targetSectors: ['Startups', 'Micro-businesses', 'Freelancers'],
  },
  {
    id: 'grow', tier: 'Grow', label: 'SME 02', segment: 'sme',
    description: 'For growing teams that need AI across multiple roles without per-seat pricing.',
    setupUSD: 1260, monthlyUSD: 750, annualUSD: 7650,
    gpu: 'Private shared infrastructure', vram: 'Shared node', gpuColor: '#3b6d11',
    userLimit: 'Up to 15 users',
    features: [
      'Everything in Spark',
      'Two AI models for different types of work',
      'Second chat interface option for your team',
      'API access — connect AI to your own tools and systems',
      'Up to 15 team members',
      'Support with 48-hour response time',
      'Monthly usage report',
    ],
    interfaces: ['AI chat interface', 'Team chat', 'Private workspace', 'API'],
    featured: true, isSME: true,
    targetSectors: ['SMEs', 'Growing teams', 'Agencies'],
  },
  {
    id: 'build', tier: 'Build', label: 'SME 03', segment: 'sme',
    description: 'For technical teams and agencies who want AI embedded in their products and workflows.',
    setupUSD: 1890, monthlyUSD: 1125, annualUSD: 11475,
    gpu: 'Private shared infrastructure', vram: 'Shared node', gpuColor: '#3b6d11',
    userLimit: 'Up to 30 users',
    features: [
      'Everything in Grow',
      'Three AI models including one optimised for technical work',
      'Developer AI assistant inside your coding environment',
      'Workflow automation — agents that run tasks in the background',
      'Webhook and system integrations',
      'Up to 30 team members',
      'Priority support with 24-hour response',
    ],
    interfaces: ['AI chat interface', 'Team chat', 'Automation agent', 'Private workspace', 'Developer assistant', 'API'],
    featured: false, isSME: true,
    targetSectors: ['Tech teams', 'Digital agencies', 'PR firms'],
  },
]

export const ENTERPRISE_PLANS: Plan[] = [
  {
    id: 'seed', tier: 'Seed', label: 'Tier 01', segment: 'enterprise',
    description: 'A complete private AI environment for smaller organisations, schools, and institutions.',
    setupUSD: 3150, monthlyUSD: 1500, annualUSD: 15300,
    gpu: 'Dedicated AI server', vram: 'Dedicated 48GB', gpuColor: '#185fa5',
    userLimit: 'Up to 25 users',
    features: [
      'Dedicated AI server allocated exclusively to your organisation',
      'Three AI models deployed and configured',
      'Document intelligence — query your knowledge base naturally',
      'API access for your own applications',
      'Private staff workspace — browser-based, no software to install',
      'Monthly performance and usage report',
      'Managed updates and round-the-clock monitoring',
    ],
    interfaces: ['AI chat interface', 'Team chat', 'Private workspace', 'API'],
    featured: false, isSME: false,
    targetSectors: ['Schools', 'NGOs', 'Small enterprises'],
  },
  {
    id: 'scale', tier: 'Scale', label: 'Tier 02', segment: 'enterprise',
    description: 'Full-organisation AI platform for enterprises deploying AI across departments.',
    setupUSD: 6300, monthlyUSD: 3150, annualUSD: 32130,
    gpu: 'Dedicated AI server (high-performance)', vram: 'Dedicated 94GB', gpuColor: '#0f6e56',
    userLimit: 'Up to 100 users',
    features: [
      'Everything in Seed, on more powerful dedicated hardware',
      'Multiple AI models running simultaneously',
      'Developer AI assistant for your engineering team',
      'Automation agents for background workflows',
      'Separate knowledge bases per department',
      'Up to 100 team members',
      'Priority support and quarterly strategy review',
    ],
    interfaces: ['AI chat interface', 'Team chat', 'Automation agents', 'Private workspace', 'Developer assistant', 'API'],
    featured: true, isSME: false,
    targetSectors: ['Enterprises', 'Hospitals', 'Financial services'],
  },
  {
    id: 'sovereign', tier: 'Sovereign', label: 'Tier 03', segment: 'enterprise',
    description: 'Maximum capacity for large organisations requiring compliance, scale, and white-glove management.',
    setupUSD: 12600, monthlyUSD: 5670, annualUSD: 57834,
    gpu: 'Dedicated AI server (maximum capacity)', vram: 'Dedicated 141GB', gpuColor: '#854f0b',
    userLimit: 'Unlimited users',
    features: [
      'Everything in Scale, on the most powerful hardware available',
      'Capacity for the most complex AI reasoning tasks',
      'Multi-department automation agent deployments',
      'Custom AI training on your organisation\'s own data',
      'Dedicated server cluster for your web and app workloads',
      'Unlimited team members',
      'Dedicated Garium account manager and custom SLA',
    ],
    interfaces: ['AI chat interface', 'Team chat', 'Automation agents', 'Private workspace', 'Developer assistant', 'API', 'Custom'],
    featured: false, isSME: false,
    targetSectors: ['Large enterprises', 'Government', 'Healthcare systems'],
  },
]

export const ALL_PLANS = [...SME_PLANS, ...ENTERPRISE_PLANS]
